### ISSUE TITLE
Matplotlib hatching issues

### ISSUE THREAD

**Issue by nickalaskreynolds** [jinshisai/SLAM#30]
## General Issue:
When running the example.py on real data, a visual horizontal pattern occurs 
<img width="400" alt="matplotlib_hatching" src="https://github.com/jinshisai/SLAM/assets/25838944/175c217a-f8be-4939-9f3b-d05d2319e5b2">

This has been observed in a few different computer systems and environments with priv. comm. with collaborators. 

## Resolution Attempt
`ax.grid(False)` and `mpl.rcParams.update({'axes.grid':False})` don't resolve the issue, leading me to believe it wasn't an actual grid being overlayed. Leading me to search for the plotting methods in the source code.

## Issue Location
The issue originates here [pvplot.py L155](https://github.com/jinshisai/SLAM/blame/a87cbe23df0e0dbf7da6bdb13f0a7b0c6ba0a56e/pvanalysis/pvplot.py#L155). The pcolormesh plot doesn't always interpolate correctly it seems, even with `nearest` set.

## Resolution
I found a small work around but it isn't ideal. Setting [kwargs_pcolormesh={'cmap':'viridis'}](https://github.com/jinshisai/SLAM/blob/a87cbe23df0e0dbf7da6bdb13f0a7b0c6ba0a56e/example_linear.py#LL40C33-L40C33) to instead be `kwargs_pcolormesh={'cmap':'viridis', shading='gouraud'}` and removing the `shading` kwarg from [pvplot.py L155](https://github.com/jinshisai/SLAM/blame/a87cbe23df0e0dbf7da6bdb13f0a7b0c6ba0a56e/pvanalysis/pvplot.py#L155) resolves the issue, but this results in an interpolation of the dataset.

The left panel is with `shading='nearest' while the right is shading='gouraud' on the same dataset.
<img width="1018" alt="2 Panel Showing Issue Resolution" src="https://github.com/jinshisai/SLAM/assets/25838944/50d1e3f9-0dfb-47de-9120-d42a0c7758e3">

Thanks for providing the SLAM code for public use, I find it is really robust and pretty easy to use/read.

**Comment by jinshisai** [comment]
Thank you for trying our code and checking it in detail! Your suggestion seems nice. We dealt with this as you suggest: we removed the shading kwarg from the pvplot.py. Now users can adopt any shading style with kwargs_pcolormesh={'cmap':'viridis', shading='SHADING_STYLE_NAME'}.
